### ISSUE TITLE
Support rendering text with FreeType

### ISSUE THREAD

**Issue by takase1121** [sammycage/plutovg#39]
I am planning to use PlutoSVG in Lite XL, which statically links FreeType. I noticed that PlutoVG is vendoring stb_truetype.h, which is slightly redundant (since we're already using FreeType, and technically PlutoSVG is being used for a purpose that [never requires text rendering](https://learn.microsoft.com/en-us/typography/opentype/spec/svg#svg-capability-requirements-and-restrictions)).

I understand that PlutoVG isn't only being used by PlutoSVG, and having text rendering support is quite important for a 2D vector library. I did some preliminary research into the code and it seems that using FreeType instead of stb_truetype.h is doable.

**Comment by sammycage** [comment]
Thank you for your feedback! I understand your concern about binary size. The use of `stb_truetype` instead of FreeType is because PlutoVG is designed to be standalone and easy to compile and modify. If you're experiencing any issues with text rendering in PlutoVG, please let me know. FreeType is only utilized in PlutoSVG for providing OpenType SVG hooks. Your input is appreciated!
